// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface NavigationMain {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    logoDarkMode: { data: Media };
    logoLightMode: { data: Media };
    menuItems?: any;
    locale: string;
    localizations?: { data: NavigationMain[] };
  };
}
export interface NavigationMain_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logoDarkMode: Media_Plain;
  logoLightMode: Media_Plain;
  menuItems?: any;
  locale: string;
  localizations?: NavigationMain_Plain[];
}

export interface NavigationMain_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logoDarkMode: number;
  logoLightMode: number;
  menuItems?: any;
  locale: string;
  localizations?: NavigationMain[];
}

export interface NavigationMain_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logoDarkMode: AdminPanelRelationPropertyModification<Media_Plain>;
  logoLightMode: AdminPanelRelationPropertyModification<Media_Plain>;
  menuItems?: any;
  locale: string;
  localizations?: NavigationMain[];
}
