// Interface automatically generated by schemas-to-ts

export enum Target {
  NewTab = 'newTab',
  SameTab = 'sameTab',}

export interface Link {
  label: string;
  url: string;
  target: Target;
}
export interface Link_Plain {
  label: string;
  url: string;
  target: Target;
}

export interface Link_NoRelations {
  label: string;
  url: string;
  target: Target;
}

