version: '3.8'

services:
  postgres:
    image: postgres:13
    ports:
      - '5555:5432'
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: "Vp5XjnPPmgEE#ytf"
      POSTGRES_DB: strapi
    volumes:
      - ./docker/data/strapi-db:/var/lib/postgresql/data