// Interface automatically generated by schemas-to-ts

export interface Translation {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    readMoreButtonLabel: string;
    locale: string;
    localizations?: { data: Translation[] };
  };
}
export interface Translation_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  readMoreButtonLabel: string;
  locale: string;
  localizations?: Translation_Plain[];
}

export interface Translation_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  readMoreButtonLabel: string;
  locale: string;
  localizations?: Translation[];
}

export interface Translation_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  readMoreButtonLabel: string;
  locale: string;
  localizations?: Translation[];
}
