// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface IconButton {
  name?: string;
  url: string;
  icon: { data: Media };
}
export interface IconButton_Plain {
  name?: string;
  url: string;
  icon: Media_Plain;
}

export interface IconButton_NoRelations {
  name?: string;
  url: string;
  icon: number;
}

