// Interface automatically generated by schemas-to-ts

export interface NotFound {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    content: any;
    locale: string;
    localizations?: { data: NotFound[] };
  };
}
export interface NotFound_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  content: any;
  locale: string;
  localizations?: NotFound_Plain[];
}

export interface NotFound_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  content: any;
  locale: string;
  localizations?: NotFound[];
}

export interface NotFound_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  content: any;
  locale: string;
  localizations?: NotFound[];
}
