// Interface automatically generated by schemas-to-ts

export interface BlogPost {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    content: any;
    slug?: any;
    locale: string;
    localizations?: { data: BlogPost[] };
  };
}
export interface BlogPost_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  content: any;
  slug?: any;
  locale: string;
  localizations?: BlogPost_Plain[];
}

export interface BlogPost_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  content: any;
  slug?: any;
  locale: string;
  localizations?: BlogPost[];
}

export interface BlogPost_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  content: any;
  slug?: any;
  locale: string;
  localizations?: BlogPost[];
}
