// Interface automatically generated by schemas-to-ts

export interface RichText {
  content: any;
}
export interface RichText_Plain {
  content: any;
}

export interface RichText_NoRelations {
  content: any;
}

