// Interface automatically generated by schemas-to-ts

export interface Footer {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    links?: any;
    socialMediaButtons?: any;
    locale: string;
    localizations?: { data: Footer[] };
  };
}
export interface Footer_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  links?: any;
  socialMediaButtons?: any;
  locale: string;
  localizations?: Footer_Plain[];
}

export interface Footer_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  links?: any;
  socialMediaButtons?: any;
  locale: string;
  localizations?: Footer[];
}

export interface Footer_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  links?: any;
  socialMediaButtons?: any;
  locale: string;
  localizations?: Footer[];
}
